name: Build and Publish

on:
  schedule:
    - cron: '0 0 */7 * *' # Regularly build weekly
  push:
  release: 
    types: [published]
  repository_dispatch:
    types: [upstream-updated]

jobs:

  # TODO: use actions/cache for Yarn
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Cache GO Packages
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: |
          make download-tools
          nvm install 12.10.0 && nvm alias default 12.10.0
        shell: bash -l {0}

      - name: Install dependencies
        run: |
          go get
          (cd ui && yarn)

      - name: Build UI
        run: make build-js

      - name: Bundle WebUI
        run: make embed-static

      - name: Check & Test
        run: |
          make test
          make check

      - name: Compile Binary
        env:
          LD_FLAGS: -w -s -X main.Version=$(git describe --tags | cut -c 2-) -X main.BuildDate=$(date "+%F-%T") -X main.Commit=${{ github.sha }} -X main.Mode=prod
        run: make build

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/gotify-*

  image-tags: 
    runs-on: ubuntu-latest
    
    outputs:
      ref: ${{ env.IMAGE_REF_TAG }}
      sha: ${{ env.IMAGE_SHA_TAG }}

    steps:
      - name: Set image ref tag
        run: |
          import os
          ref = os.environ['GITHUB_REF'].split('/')[1:]
          if ref[0] == 'heads':
              if ref[1] == 'master':
                  os.environ['IMAGE_REF_TAG'] = 'latest'
              else:
                  os.environ['IMAGE_REF_TAG'] = '-'.join(ref[1:])
          elif ref[0] == 'pull':
              os.environ['IMAGE_REF_TAG'] = f'pr-{"-".join(ref[1:])}'
          elif ref[0] == 'tags':
              os.environ['IMAGE_REF_TAG'] = ref[1]
        shell: python3 {0}

      - name: Set image SHA tag
        run: |
          import os
          sha = os.environ['GITHUB_SHA'][:7]
          os.environ['IMAGE_SHA_TAG'] = f'git-{sha}'
        shell: python3 {0}

  # Build container image
  build-amd64-image:
    runs-on: ubuntu-latest
    needs: build-artifacts
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Build linux/amd64 image
        run: |
          cp build/gotify-linux-amd64 docker/gotify-app
          docker build -f docker/Dockerfile -t gotify:amd64 docker/
          rm docker/gotify-app

      - name: Export image
        run: docker save -o="docker/gotify-amd64-container-image.tar" gotify

      - name: Upload Image
        uses: actions/upload-artifact@v2
        with:
          name: gotify-amd64-container-image
          path: docker/gotify-amd64-container-image.tar

  # TODO: Multi-platform build

  # Push image to different registries
  docker-hub:
    runs-on: ubuntu-latest
    needs: [build-amd64-image, image-tags]
    steps:
      - name: Get the amd64 images
        uses: actions/download-artifact@v2
        with:
          name: gotify-amd64-container-image

      - name: Import the image
        run: docker load -i gotify-amd64-container-image.tar

      - name: Tag the image
        run: |
          docker tag gotify:amd64 ${{ secrets.DOCKER_USERNAME }}/gotify-server:${{ needs.image-tags.outputs.ref }}
          docker tag gotify:amd64 ${{ secrets.DOCKER_USERNAME }}/gotify-server:${{ needs.image-tags.outputs.sha }}

      - name: Login docker cli
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: docker push ${{ secrets.DOCCKER_USERNAME }}/gotify-server

  gce-cr:
    runs-on: ubuntu-latest
    needs: [build-amd64-image, image-tags]
    env:
      GCR_HOST: us.gcr.io
    steps:
      - name: Get the amd64 images
        uses: actions/download-artifact@v2
        with:
          name: gotify-amd64-container-image

      - name: Import the image
        run: docker load -i gotify-amd64-container-image.tar

      - name: Tag the image
        run: |
          docker tag gotify:amd64 ${{ env.GCR_HOST }}/${{ secrets.GCE_PROJECT }}/gotify-server:${{ needs.image-tags.outputs.ref }}
          docker tag gotify:amd64 ${{ env.GCR_HOST }}/${{ secrets.GCE_PROJECT }}/gotify-server:${{ needs.image-tags.outputs.sha }}

      - name: Login docker cli
        run: docker login --username _json_key --password ${{ secrets.GCE_CR_TOKEN }} https://${{ env.GCR_HOST }}

      - name: Push image
        run: docker push ${{ env.GCR_HOST }}/${{ secrets.DOCCKER_USERNAME }}/gotify-server